# Generated by Django 6.0 on 2026-02-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(choices=[('a', 'python'), ('b', 'django')], help_text='ENTER A VALID TITLE', max_length=70),
        ),
    ]
