# Generated by Django 6.0 on 2026-02-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_article_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='auther',
            new_name='author',
        ),
    ]
