# Generated by Django 6.0 on 2026-02-19 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 19, 16, 56, 46, 669208, tzinfo=datetime.timezone.utc)),
        ),
    ]
