# Generated by Django 6.0 on 2026-02-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_rename_auther_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='ENTER A VALID TITLE ', max_length=70),
        ),
    ]
