# Generated by Django 6.0 on 2026-02-19 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_category_alter_article_pub_date_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 19, 17, 16, 27, 448150, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(choices=[('a', 'python'), ('b', 'django'), ('c', 'animals'), ('d', 'laptop')], help_text='ENTER A VALID TITLE', max_length=70),
        ),
    ]
