# Generated by Django 6.0 on 2026-02-19 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 19, 18, 25, 38, 155947, tzinfo=datetime.timezone.utc)),
        ),
    ]
