# Generated by Django 6.0 on 2026-02-19 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 19, 20, 54, 58, 291120, tzinfo=datetime.timezone.utc)),
        ),
    ]
